version: "3"
    #        www:
    #       build: .
    #       ports:
    #           - 8001:80
    #       volumes:
    #           - ./www:/var/www/html/
    #       networks:
    #           - default
services:
  db_for_wp:
    image: mysql:5.7
    container_name: wordpress-db
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rudolf
    volumes:
#      - ./db_import:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    depends_on:
        - db_for_wp
    image: phpmyadmin/phpmyadmin
    links:
     - db_for_wp:db
    ports:
     - "8001:80"
    environment:
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress
     MYSQL_ROOT_PASSWORD: rudolf
    networks:
      - default
  wordpress:
    depends_on:
      - db_for_wp
    image: wordpress
    container_name: devrev-wp
    ports:
      - "8000:80"
    restart: always
    environment:
#      VIRTUAL_HOST: devrev.pl
      WORDPRESS_DB_HOST: db_for_wp:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./data:/data
      - ./wp-data:/var/www/html
#      - ./bourbon:/var/www/html/wp-content/themes/bourbon
#      - ./elementor:/var/www/html/wp-content/plugins/elementor
#      - ./elementor-pro:/var/www/html/wp-content/plugins/elementor-pro
    networks:
      - default
#volumes:
#  mysql_data: /


